export const ADD_ARTICLE = "ADD_ARTICLE";
export const REMOVE_ARTICLE = "REMOVE_ARTICLE";
export const DATA_LOADED = "DATA_LOADED";
export const DATA_REQUESTED = "DATA_REQUESTED";
export const USERS_DATA_LOADED = "USERS_DATA_LOADED";
export const USERS_DATA_REQUESTED = "USERS_DATA_REQUESTED";
